export const Sections = [
  {
    id: 1,
    level: "A1",
    sectionNumber: 1,
    title: "Numbers",
    Image: "/numbers.svg",
    isContined: true,
    jobNumber: 5,
    jobDone: 3,
    chapters: [
      {
        id: 1,
        name: "Chapter 1",
        isContinued: true,
        description: "abdifatah dahir muse baarre ",
        color: "bg-green-500",
        lessons: [
          { id: 1, name: "phrases", status: "start" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
      {
        id: 2,
        name: "Chapter 2",
        isContinued: false,
        description: "good and better best for amazin things",
        color: "bg-blue-500",
        lessons: [
          { id: 1, name: "good", status: "LOCKED" },
          { id: 2, name: "good 2", status: "LOCKED" },
          { id: 3, name: "good 3", status: "LOCKED" },
        ],
      },
      {
        id: 3,
        name: "Chapter 3",
        isContinued: false,
        description: "analysisng better anamzin things to do his job ",
        color: "bg-yellow-300",
        lessons: [
          { id: 1, name: "better", status: "LOCKED" },
          { id: 2, name: "better 2", status: "LOCKED" },
          { id: 3, name: "better 3", status: "LOCKED" },
        ],
      },
    ],
  },
  {
    id: 2,
    level: "B2",
    sectionNumber: 2,
    title: "big numbers",
    Image: "/cartoon.png",
    isContined: false,
    jobNumber: 5,
    jobDone: 3,
    chapters: [
      {
        id: 1,
        name: "Chapter 1",
        isContinued: true,
        description: "abdifatah ",
        color: "bg-green-500",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
      {
        id: 2,
        name: "Chapter 2",
        isContinued: false,
        description: "good a",
        color: "bg-blue-500",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
      {
        id: 3,
        name: "Chapter 3",
        isContinued: false,
        description: "analysisng  ",
        color: "bg-yellow-300",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
    ],
  },
  {
    id: 3,
    level: "C3",
    sectionNumber: 3,
    title: "Addition",
    Image: "/parent.png",
    isContined: false,
    jobNumber: 5,
    jobDone: 3,
    chapters: [
      {
        id: 1,
        name: "Chapter 1",
        isContinued: true,
        description: "abdifatah ",
        color: "bg-green-500",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
      {
        id: 2,
        name: "Chapter 2",
        isContinued: false,
        description: "good a",
        color: "bg-blue-500",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
      {
        id: 3,
        name: "Chapter 3",
        isContinued: false,
        description: "analysisng  ",
        color: "bg-yellow-300",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
    ],
  },
  {
    id: 4,
    level: "A3",
    sectionNumber: 4,
    title: "Substruction",
    Image: "/cry.png",
    isContined: false,
    jobNumber: 5,
    jobDone: 3,
    chapters: [
      {
        id: 1,
        name: "Chapter 1",
        isContinued: true,
        description: "abdifatah ",
        color: "bg-green-500",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
      {
        id: 2,
        name: "Chapter 2",
        isContinued: false,
        description: "good a",
        color: "bg-blue-500",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
      {
        id: 3,
        name: "Chapter 3",
        isContinued: false,
        description: "analysisng  ",
        color: "bg-yellow-300",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
    ],
  },
  {
    id: 5,
    level: "B5",
    sectionNumber: 5,
    title: "Multiplication",
    Image: "/diin.png",
    isContined: false,
    jobNumber: 5,
    jobDone: 3,
    chapters: [
      {
        id: 1,
        name: "Chapter 1",
        isContinued: true,
        description: "abdifatah ",
        color: "bg-green-500",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
      {
        id: 2,
        name: "Chapter 2",
        isContinued: false,
        description: "good a",
        color: "bg-blue-500",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
      {
        id: 3,
        name: "Chapter 3",
        isContinued: false,
        description: "analysisng  ",
        color: "bg-yellow-300",
        lessons: [
          { id: 1, name: "phrases", status: "LOCKED" },
          { id: 2, name: "phrases 2", status: "LOCKED" },
          { id: 3, name: "phrases 3", status: "LOCKED" },
        ],
      },
    ],
  },
];
